### ISSUE TITLE
npm adduser fails

### ISSUE THREAD

**Issue by gmaggess** [npm/npm-registry-couchapp#103]
Hi Gurus,

I have installed couchdb 1.0.4 - not sure if it's supported - node v0.10.5, and npm v1.2.18. I've managed to run replicate [https://github.com/mikeal/replicate] successfully, but now I'm having issues to create adduser with npm. I only have admin setup on my server so far and secure_rewrite is false. I guess I've done my homework, but I guess something simple might be missing.

When I run 'npm adduser' I'm facing the 401 below. If the user was previously created using 'curl -X PUT 'http://admin:Welcome1@machine:5984/_users/org.couchdb.user:gmaggess' -d '{"name": "gmaggess","password": "welcome1", "type": "user","roles": ["editor"]}', then I get a 404. Does anyone have a clue about what could've been happening here?

$ sudo npm adduser --verbose --registry http://admin:Welcome1@machine:5984/registry
npm info it worked if it ends with ok
npm verb cli [ '/scratch/gmaggess/node-v0.10.5-linux-x64/bin/node',
npm verb cli   '/scratch/gmaggess/node-v0.10.5-linux-x64/bin/npm',
npm verb cli   'adduser',
npm verb cli   '--verbose',
npm verb cli   '--registry',
npm verb cli   'http://admin:Welcome1@machine:5984/registry' ]
npm info using npm@1.2.18
npm info using node@v0.10.5
Username: gmaggess
Password:
Email: george.maggessy@gmail.com
npm verb adduser before first PUT { name: 'gmaggess',
npm verb adduser   salt: 'XXXXX',
npm verb adduser   password_sha: 'XXXXX',
npm verb adduser   email: 'george.maggessy@gmail.com',
npm verb adduser   _id: 'org.couchdb.user:gmaggess',
npm verb adduser   type: 'user',
npm verb adduser   roles: [],
npm verb adduser   date: '2013-05-04T00:02:46.928Z' }
npm verb url raw /-/user/org.couchdb.user:gmaggess
npm verb url resolving [ 'http://admin:Welcome1@machine:5984/registry/',
npm verb url resolving   './-/user/org.couchdb.user:gmaggess' ]
npm verb url resolved http://admin:Welcome1@machine:5984/registry/-/user/org.couchdb.user:gmaggess
npm info trying registry request attempt 1 at 17:02:46
npm http PUT http://admin:Welcome1@machine:5984/registry/-/user/org.couchdb.user:gmaggess
npm info retry will retry, error on last attempt: Error: Parse Error
npm info trying registry request attempt 2 at 17:02:57
npm http PUT http://admin:Welcome1@machine:5984/registry/-/user/org.couchdb.user:gmaggess
npm http 409 http://admin:Welcome1@machine:5984/registry/-/user/org.couchdb.user:gmaggess
npm verb adduser update existing user
npm verb url raw /-/user/org.couchdb.user:gmaggess
npm verb url resolving [ 'http://admin:Welcome1@machine:5984/registry/',
npm verb url resolving   './-/user/org.couchdb.user:gmaggess' ]
npm verb url resolved http://admin:Welcome1@machine:5984/registry/-/user/org.couchdb.user:gmaggess
npm info trying registry request attempt 1 at 17:02:57
npm http GET http://admin:Welcome1@machine:5984/registry/-/user/org.couchdb.user:gmaggess
npm http 401 http://admin:Welcome1@machine:5984/registry/-/user/org.couchdb.user:gmaggess
npm verb adduser back [ [Error: unauthorized Name or password is incorrect.: registry/-/user/org.couchdb.user:gmaggess],
npm verb adduser   { error: 'unauthorized',
npm verb adduser     reason: 'Name or password is incorrect.' },
npm verb adduser   '{"error":"unauthorized","reason":"Name or password is incorrect."}\n' ]
npm WARN adduser Incorrect username or password
npm WARN adduser You can reset your account by visiting:
npm WARN adduser
npm WARN adduser     http://admin.npmjs.org/reset
npm WARN adduser
npm ERR! Error: unauthorized Name or password is incorrect.: registry/-/user/org.couchdb.user:gmaggess
npm ERR!     at RegClient.<anonymous> (/scratch/gmaggess/node-v0.10.5-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:269:14)
npm ERR!     at Request.self.callback (/scratch/gmaggess/node-v0.10.5-linux-x64/lib/node_modules/npm/node_modules/request/index.js:142:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/scratch/gmaggess/node-v0.10.5-linux-x64/lib/node_modules/npm/node_modules/request/index.js:856:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/scratch/gmaggess/node-v0.10.5-linux-x64/lib/node_modules/npm/node_modules/request/index.js:808:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:895:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! System Linux 2.6.39-300.20.1.el6uek.x86_64
npm ERR! command "/scratch/gmaggess/node-v0.10.5-linux-x64/bin/node" "/scratch/gmaggess/node-v0.10.5-linux-x64/bin/npm" "adduser" "--verbose" "--registry" "http://admin:Welcome1@machine:5984/registry"
npm ERR! cwd /scratch/gmaggess
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm verb exit [ 1, true ]
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /scratch/gmaggess/npm-debug.log
npm ERR! not ok code 0

Cheers,
George

**Comment by johnzheng1975** [comment]
$ npm owner add john.zheng uppercasemej --registry  http://**admin:joh**n@XXXXXX:5984/registry/_design/app/_rewrite
+ john.zheng (uppercasemej)
