### ISSUE TITLE
Unable to setup private npm

### ISSUE THREAD

**Issue by codematix** [npm/npm-registry-couchapp#190]
Hi,

I am having an issue getting my private NPM to run. I have installed CouchDB and configured it to replicate from Skim DB. However, when I attempt to login using `npm login`, it throws the error:

```
npm ERR! Error: illegal_database_name Name: '-'. Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter.: -/user/org.couchdb.user:rkini
npm ERR!     at RegClient.<anonymous> (/home/codematix/.nvm/v0.10.31/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:300:14)
npm ERR!     at Request._callback (/home/codematix/.nvm/v0.10.31/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:238:65)
npm ERR!     at Request.self.callback (/home/codematix/.nvm/v0.10.31/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/home/codematix/.nvm/v0.10.31/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/home/codematix/.nvm/v0.10.31/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:943:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
```

It seems to be using `http://localhost:5984` as the registry but I have configured the registry to be `http://localhost:5984/registry/_design/ap/_rewrite`.

Not sure how I could proceed. Please help!

**Comment by dwick** [comment]
:+1: @kmctown

**Comment by terinjokes** [comment]
@kmctown If you don't set up the vhost, you need to tell npm to connect to the full path to the couchapp, including "/registry/_design/app/_rewrite".
