### ISSUE TITLE
replicating https://skimdb.npmjs.com/registry fails with bad match

### ISSUE THREAD

**Issue by chongj615** [npm/npm-registry-couchapp#215]
Hi,

We had been replicating https://skimdb.npmjs.com/registry for a while now, but around Nov 24th, 2014, we start getting the error below, any idea what?  I check that we can connect skimdb.npmjs.com via curl
curl https://skimdb.npmjs.com/registry/
{"db_name":"registry","doc_count":118081,"doc_del_count":378,"update_seq":691122,"purge_seq":0,"compact_running":false,"disk_size":1016000635,"data_size":425905206,"instance_start_time":"1417565593480626","disk_format_version":6,"committed_update_seq":691122}

error from coucdb log

*\* Reason for termination =
*\* {{badmatch,
        {error,
            {asn1,
                {'Type not compatible with table constraint',
                    {{component,'Type'},
                     {value,{5,<<>>}},
                     {unique_name_and_value,id,{1,2,840,113549,1,1,11}}}}}}},
    [{public_key,pkix_decode_cert,2},
     {ssl_certificate,trusted_cert_and_path,3},
     {ssl_handshake,certify,7},
     {ssl_connection,certify,2},
     {ssl_connection,next_state,3},
     {gen_fsm,handle_msg,7},
     {proc_lib,init_p_do_apply,3}]}

[Mon, 08 Dec 2014 21:58:19 GMT] [error] [<0.154.0>] {error_report,<0.62.0>,
                     {<0.154.0>,crash_report,
                      [[{initial_call,{ssl_connection,init,['Argument__1']}},
                        {pid,<0.154.0>},
                        {registered_name,[]},
                        {error_info,
                         {exit,
                          {{badmatch,
                            {error,
                             {asn1,
                              {'Type not compatible with table constraint',
                               {{component,'Type'},
                                {value,{5,<<>>}},
                                {unique_name_and_value,id,
                                 {1,2,840,113549,1,1,11}}}}}}},
                           [{public_key,pkix_decode_cert,2},
                            {ssl_certificate,trusted_cert_and_path,3},
                            {ssl_handshake,certify,7},
                            {ssl_connection,certify,2},
                            {ssl_connection,next_state,3},
                            {gen_fsm,handle_msg,7},
                            {proc_lib,init_p_do_apply,3}]},
                          [{gen_fsm,terminate,7},
                           {proc_lib,init_p_do_apply,3}]}},
                        {ancestors,[ssl_connection_sup,ssl_sup,<0.63.0>]},
                        {messages,[]},
                        {links,[<0.67.0>]},
                        {dictionary,[]},
                        {trap_exit,false},
                        {status,running},
                        {heap_size,1597},
                        {stack_size,24},
                        {reductions,981}],
                       []]}}
[Mon, 08 Dec 2014 21:58:19 GMT] [error] [<0.67.0>] {error_report,<0.62.0>,
                    {<0.67.0>,supervisor_report,
                     [{supervisor,{local,ssl_connection_sup}},
                      {errorContext,child_terminated},
                      {reason,
                       {{badmatch,
                         {error,
                          {asn1,
                           {'Type not compatible with table constraint',
                            {{component,'Type'},
                             {value,{5,<<>>}},
                              {1,2,840,113549,1,1,11}}}}}}},
                        [{public_key,pkix_decode_cert,2},
                         {ssl_certificate,trusted_cert_and_path,3},
                         {ssl_handshake,certify,7},
                         {ssl_connection,certify,2},
                         {ssl_connection,next_state,3},
                         {gen_fsm,handle_msg,7},
                         {proc_lib,init_p_do_apply,3}]}},
                      {offender,
                       [{pid,<0.154.0>},
                        {name,undefined},
                        {mfargs,{ssl_connection,start_link,undefined}},
                        {restart_type,temporary},
                        {shutdown,4000},
                        {child_type,worker}]}]}}
[Mon, 08 Dec 2014 21:58:19 GMT] [error] [<0.130.0>] *\* Generic server <0.130.0> terminating
*\* Last message in was {send_req,
                           {{url,"https://skimdb.npmjs.com/registry/",
                                "skimdb.npmjs.com",443,undefined,undefined,
                                "/registry/",https,hostname},
                            [{"Accept","application/json"},
                             {"User-Agent","CouchDB/1.5.0"}],
                            head,<<>>,
                            [{response_format,binary},
                             {inactivity_timeout,30000},
                             {is_ssl,true},
                             {socket_options,
                                 [{keepalive,true},{nodelay,false}]},
                             {ssl_options,[{depth,3},{verify,verify_none}]}],
                            infinity}}
*\* When Server state == {state,"skimdb.npmjs.com",443,undefined,
                               #Ref<0.0.0.229>,false,undefined,[],true,
                               undefined,false,[],
                               {[],[]},
                               undefined,idle,undefined,<<>>,0,0,[],undefined,
                               undefined,undefined,undefined,false,undefined,
                               undefined,<<>>,undefined,false,undefined,0,
                               undefined}

**Comment by gilShin** [comment]
@chongj615 

Upgraded and replication completed successfully but can install packages using:
npm --registry http://localhost:5984/registry/_design/app/_rewrite install grunt

I get the insecure rewrites error message (configures secure_rewrites = false in all available *.ini files and restarted couchdb):
npm ERR! Error: insecure_rewrite_rule too many ../.. segments: registry/_design/app/_rewrite/grunt
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:14)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:442:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "--registry" "http://localhost:5984/registry/_design/app/_rewrite" "install" "grunt"
npm ERR! cwd /tmp/gridfs
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/gridfs/npm-debug.log
npm ERR! not ok code 0


Any help?
