### ISSUE TITLE
scopes don't work

### ISSUE THREAD

**Issue by MarkSwanson** [npm/npm-registry-couchapp#240]
npm publish works fine - so authentication is working.

As the same user, I try to publish in a scope - so I:
- edit package.json
- change name from "package-test" to "@deleteme/package-test"
- npm publish

And I get an authentication error: Error: unauthorized Name or password is incorrect.: @deleteme/package-test

npm verb stack     at CachingRegistryClient.<anonymous> (/home/deleteme/node-v0.12.7-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
npm verb stack     at Request._callback (/home/deleteme/node-v0.12.7-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
npm verb stack     at Request.self.callback (/home/deleteme/node-v0.12.7-linux-x64/lib/node_modules/npm/node_modules/request/request.js:354:22)
npm verb stack     at Request.emit (events.js:110:17)
npm verb stack     at Request.<anonymous> (/home/deleteme/node-v0.12.7-linux-x64/lib/node_modules/npm/node_modules/request/request.js:1207:14)
npm verb stack     at Request.emit (events.js:129:20)
npm verb stack     at IncomingMessage.<anonymous> (/home/deleteme/node-v0.12.7-linux-x64/lib/node_modules/npm/node_modules/request/request.js:1153:12)
npm verb stack     at IncomingMessage.emit (events.js:129:20)

Should this work?

Thanks.

**Comment by MarkSwanson** [comment]
I found the problem and solution.

For the initial publish:
- scope MUST be a role.
  - example: deleteme is the scope, so the user must have roles: ["deleteme"]

For updates:
- project.json MUST contain a maintainers property.
- maintainer must contain "name": user
  - example: "maintainers": [ {"name": "deleteme"} ]

You can see why these are required by delving into the registry validate_update_doc _design/scratch code.
