### ISSUE TITLE
Scoped packages user acccess

### ISSUE THREAD

**Issue by taemtha** [npm/npm-registry-couchapp#250]
Hi,

is it possible to work with scoped packages and the npm-registry-couchapp?

I set up the couchdb server according to the README.md.

Unscoped packages can be published without issues, but if i try to publish scoped packages, it won't work. Npm tells me that my user is not authorized to modify this package.

I found no way to authorize the user. Is there a way so solve this, or is it not possible with the npm-registry-couchapp?

Here is the log output of the npm publish command:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/michael/.nvm/versions/node/v4.2.3/bin/node',
1 verbose cli   '/Users/michael/.nvm/versions/node/v4.2.3/bin/npm',
1 verbose cli   'pub' ]
2 info using npm@3.5.2
3 info using node@v4.2.3
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/michael/dev/test',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/michael/.npm/@idms/test/1.0.0/package.tgz not in flight; packing
9 info lifecycle @idms/test@1.0.0~prepublish: @idms/test@1.0.0
10 silly lifecycle @idms/test@1.0.0~prepublish: no script for prepublish, continuing
11 verbose tar pack [ '/Users/michael/.npm/@idms/test/1.0.0/package.tgz',
11 verbose tar pack   '/Users/michael/dev/test' ]
12 verbose tarball /Users/michael/.npm/@idms/test/1.0.0/package.tgz
13 verbose folder /Users/michael/dev/test
14 verbose addLocalTarball adding from inside cache /Users/michael/.npm/@idms/test/1.0.0/package.tgz
15 silly cache afterAdd @idms/test@1.0.0
16 verbose afterAdd /Users/michael/.npm/@idms/test/1.0.0/package/package.json not in flight; writing
17 verbose afterAdd /Users/michael/.npm/@idms/test/1.0.0/package/package.json written
18 silly publish { name: '@idms/test',
18 silly publish   version: '1.0.0',
18 silly publish   description: 'test package',
18 silly publish   main: 'index.js',
18 silly publish   scripts: { test: 'echo "Error: no test specified" && exit 1' },
18 silly publish   maintainers: [ { name: 'mmatzka' } ],
18 silly publish   author: '',
18 silly publish   license: 'ISC',
18 silly publish   readme: 'ERROR: No README data found!',
18 silly publish   _id: '@idms/test@1.0.0',
18 silly publish   _shasum: 'f0d1fb3cd55b7bfc3645263e1bd0160e7e76fce8',
18 silly publish   _from: '.' }
19 verbose getPublishConfig undefined
20 silly mapToRegistry name @idms/test
21 silly mapToRegistry scope (from package name) @idms
22 silly mapToRegistry registry http://localhost:5984/registry/_design/app/_rewrite
23 silly mapToRegistry uri http://localhost:5984/registry/_design/app/_rewrite/@idms%2ftest
24 verbose publish registryBase http://localhost:5984/registry/_design/app/_rewrite/
25 silly publish uploading /Users/michael/.npm/@idms/test/1.0.0/package.tgz
26 verbose request uri http://localhost:5984/registry/_design/app/_rewrite/@idms%2ftest
27 verbose request sending authorization for write operation
28 info attempt registry request try #1 at 6:03:53 PM
29 verbose request id fbd9b470d30f9e39
30 http request PUT http://localhost:5984/registry/_design/app/_rewrite/@idms%2ftest
31 http 403 http://localhost:5984/registry/_design/app/_rewrite/@idms%2ftest
32 verbose headers { server: 'CouchDB/1.6.1 (Erlang OTP/17)',
32 verbose headers   date: 'Sun, 10 Jan 2016 17:03:53 GMT',
32 verbose headers   'content-type': 'application/json',
32 verbose headers   'content-length': '304',
32 verbose headers   'cache-control': 'must-revalidate' }
33 verbose request invalidating /Users/michael/.npm/localhost_5984/registry/_design/app/_rewrite/_40idms_252ftest on PUT
34 error publish Failed PUT 403
35 verbose stack Error: forbidden user: mmatzka not authorized to modify @idms/test
35 verbose stack Added: _id
35 verbose stack Added: name
35 verbose stack Added: description
35 verbose stack Added: dist-tags
35 verbose stack Added: versions
35 verbose stack Added: readme
35 verbose stack Added: maintainers
35 verbose stack Added: time
35 verbose stack Added: license
35 verbose stack Added: readmeFilename
35 verbose stack Added: _revisions
35 verbose stack Added: _attachments
35 verbose stack Added: users: @idms/test
35 verbose stack     at makeError (/Users/michael/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
35 verbose stack     at CachingRegistryClient.<anonymous> (/Users/michael/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
35 verbose stack     at Request._callback (/Users/michael/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
35 verbose stack     at Request.self.callback (/Users/michael/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/request/request.js:198:22)
35 verbose stack     at emitTwo (events.js:87:13)
35 verbose stack     at Request.emit (events.js:172:7)
35 verbose stack     at Request.<anonymous> (/Users/michael/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/request/request.js:1082:10)
35 verbose stack     at emitOne (events.js:82:20)
35 verbose stack     at Request.emit (events.js:169:7)
35 verbose stack     at IncomingMessage.<anonymous> (/Users/michael/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/request/request.js:1009:12)
36 verbose statusCode 403
37 verbose pkgid @idms/test
38 verbose cwd /Users/michael/dev/test
39 error Darwin 14.5.0
40 error argv "/Users/michael/.nvm/versions/node/v4.2.3/bin/node" "/Users/michael/.nvm/versions/node/v4.2.3/bin/npm" "pub"
41 error node v4.2.3
42 error npm  v3.5.2
43 error code E403
44 error forbidden user: mmatzka not authorized to modify @idms/test
44 error Added: _id
44 error Added: name
44 error Added: description
44 error Added: dist-tags
44 error Added: versions
44 error Added: readme
44 error Added: maintainers
44 error Added: time
44 error Added: license
44 error Added: readmeFilename
44 error Added: _revisions
44 error Added: _attachments
44 error Added: users: @idms/test
45 error If you need help, you may report this error at:
45 error     <https://github.com/npm/npm/issues>
46 verbose exit [ 1, true ]```

**Comment by taemtha** [comment]
My issue, i forgot to safe the changed user account documents in the couchdb. Scoped packages are working as well.
