### ISSUE TITLE
npm dist-tags command does not work on private registry

### ISSUE THREAD

**Issue by crsandeep** [npm/npm-registry-couchapp#260]
dist-tag makes call to http://<hostname>:5984/registry/_design/app/_rewrite/-/package/<module-name>/dist-tags which returns 404. Finding, adding or removing dist-tags are failing for private registry. Here is the debug log

0 info it worked if it ends with ok
1 verbose cli [ '/home/<user>/.nvm/versions/node/v6.2.1/bin/node',
1 verbose cli   '/home/<user>/.nvm/versions/node/v6.2.1/bin/npm',
1 verbose cli   'dist-tag',
1 verbose cli   'ls',
1 verbose cli   'atom-nsp' ]
2 info using npm@3.9.3
3 info using node@v6.2.1
4 verbose config Skipping project config: /home/<user>/.npmrc. (matches userconfig)
5 silly mapToRegistry name atom-nsp
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry http://<hostname>:5984/registry/_design/app/_rewrite
8 silly mapToRegistry data Result {
8 silly mapToRegistry   raw: 'atom-nsp',
8 silly mapToRegistry   scope: null,
8 silly mapToRegistry   name: 'atom-nsp',
8 silly mapToRegistry   rawSpec: '',
8 silly mapToRegistry   spec: 'latest',
8 silly mapToRegistry   type: 'tag' }
9 silly mapToRegistry uri http://<hostname>:5984/registry/_design/app/_rewrite/atom-nsp
10 verbose request uri http://<hostname>:5984/registry/_design/app/_rewrite/-/package/atom-nsp/dist-tags
11 verbose request no auth needed
12 info attempt registry request try #1 at 1:11:13 AM
13 verbose request id e6325b05187ff170
14 http request GET http://<hostname>:5984/registry/_design/app/_rewrite/-/package/atom-nsp/dist-tags
15 http 404 http://<hostname>:5984/registry/_design/app/_rewrite/-/package/atom-nsp/dist-tags
16 verbose headers { server: 'CouchDB/1.6.1 (Erlang OTP/R16B03)',
16 verbose headers   date: 'Thu, 16 Jun 2016 08:11:13 GMT',
16 verbose headers   'content-type': 'application/json',
16 verbose headers   'content-length': '41',
16 verbose headers   'cache-control': 'must-revalidate' }
17 error dist-tag ls Couldn't get dist-tag data for atom-nsp
18 verbose stack Error: 404 Not Found: -
18 verbose stack     at makeError (/home/<user>/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
18 verbose stack     at CachingRegistryClient.<anonymous> (/home/<user>/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:250:14)
18 verbose stack     at Request._callback (/home/<user>/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
18 verbose stack     at Request.self.callback (/home/<user>/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/request/request.js:200:22)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at Request.emit (events.js:191:7)
18 verbose stack     at Request.<anonymous> (/home/<user>/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/request/request.js:1067:10)
18 verbose stack     at emitOne (events.js:101:20)
18 verbose stack     at Request.emit (events.js:188:7)
18 verbose stack     at IncomingMessage.<anonymous> (/home/<user>/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/request/request.js:988:12)
19 verbose statusCode 404
20 verbose pkgid -
21 verbose cwd /home/<user>
22 error Linux 3.13.0-24-generic
23 error argv "/home/<user>/.nvm/versions/node/v6.2.1/bin/node" "/home/<user>/.nvm/versions/node/v6.2.1/bin/npm" "dist-tag" "ls" "atom-nsp"
24 error node v6.2.1
25 error npm  v3.9.3
26 error code E404
27 error 404 Not Found: -
28 verbose exit [ 1, true ]

**Comment by crsandeep** [comment]
closing since I found out the issue. Required views were not there, it got fixed after adding them
