### ISSUE TITLE
 throw new Error('Must set DEPLOY_VERSION env to `git describe` output')

### ISSUE THREAD

**Issue by sudheerkrishnabattu** [npm/npm-registry-couchapp#263]
Hi,

I am trying to run the command couchapp push registry/app.js http://localhost:5984/registry I'm getting below error message. I made the change based on the answer provided by Terinjokes https://github.com/npm/npm-registry-couchapp/commit/e5e41630fc70eec41264c813f70664340a906a40
 and I'm still having the issue. Please let me know what needs to be done to resolve the issue,

My npm version 3.10.6 and node js version v0.10.25

/npm-repo/npmjs.org/registry/app.js:15
  throw new Error('Must set DEPLOY_VERSION env to `git describe` output')
        ^
Error: Must set DEPLOY_VERSION env to `git describe` output
    at Object.<anonymous> (/npm-repo/npmjs.org/registry/app.js:15:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/couchapp/bin.js:175:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

Thanks in advance..

Sudheer

**Comment by terinjokes** [comment]
In the shell you're running these steps in, is `DEPLOY_VERSION` set?

```
echo $DEPLOY_VERSION
```

**Comment by nothingweb** [comment]
I have the same problem.Some people solved this problem?

**Comment by delonakc** [comment]
````
DEPLOY_VERSION='git describe --tags' couchapp push registry/app.js http://127.0.0.1:5984/registry
````
you can try this.

**Comment by wariorx** [comment]
If this error persists after setting the env variable, you can also hard code it within app.js by adding this before the `if` statement

`process.env.DEPLOY_VERSION = 'git describe --tags' `
